// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: festivals.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFestival = `-- name: CreateFestival :one
INSERT INTO festivals (
    slug, name, date_type, region, heritage_type, festival_type,
    summary, story, what_to_expect, how_to_participate, practical_info,
    cover_image_url, gallery_images, video_embeds, is_published
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
) RETURNING id, slug, name, date_type, region, heritage_type, festival_type, summary, story, what_to_expect, how_to_participate, practical_info, cover_image_url, gallery_images, video_embeds, is_published, created_at, usual_month, date_2026_start, date_2026_end
`

type CreateFestivalParams struct {
	Slug             string      `json:"slug"`
	Name             string      `json:"name"`
	DateType         string      `json:"dateType"`
	Region           string      `json:"region"`
	HeritageType     string      `json:"heritageType"`
	FestivalType     string      `json:"festivalType"`
	Summary          string      `json:"summary"`
	Story            pgtype.Text `json:"story"`
	WhatToExpect     pgtype.Text `json:"whatToExpect"`
	HowToParticipate pgtype.Text `json:"howToParticipate"`
	PracticalInfo    pgtype.Text `json:"practicalInfo"`
	CoverImageUrl    pgtype.Text `json:"coverImageUrl"`
	GalleryImages    []byte      `json:"galleryImages"`
	VideoEmbeds      []byte      `json:"videoEmbeds"`
	IsPublished      pgtype.Bool `json:"isPublished"`
}

func (q *Queries) CreateFestival(ctx context.Context, arg CreateFestivalParams) (Festival, error) {
	row := q.db.QueryRow(ctx, createFestival,
		arg.Slug,
		arg.Name,
		arg.DateType,
		arg.Region,
		arg.HeritageType,
		arg.FestivalType,
		arg.Summary,
		arg.Story,
		arg.WhatToExpect,
		arg.HowToParticipate,
		arg.PracticalInfo,
		arg.CoverImageUrl,
		arg.GalleryImages,
		arg.VideoEmbeds,
		arg.IsPublished,
	)
	var i Festival
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.DateType,
		&i.Region,
		&i.HeritageType,
		&i.FestivalType,
		&i.Summary,
		&i.Story,
		&i.WhatToExpect,
		&i.HowToParticipate,
		&i.PracticalInfo,
		&i.CoverImageUrl,
		&i.GalleryImages,
		&i.VideoEmbeds,
		&i.IsPublished,
		&i.CreatedAt,
		&i.UsualMonth,
		&i.Date2026Start,
		&i.Date2026End,
	)
	return i, err
}

const deleteFestival = `-- name: DeleteFestival :exec
DELETE FROM festivals
WHERE id = $1
`

func (q *Queries) DeleteFestival(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteFestival, id)
	return err
}

const getFestivalByID = `-- name: GetFestivalByID :one
SELECT id, slug, name, date_type, region, heritage_type, festival_type, summary, story, what_to_expect, how_to_participate, practical_info, cover_image_url, gallery_images, video_embeds, is_published, created_at, usual_month, date_2026_start, date_2026_end FROM festivals
WHERE id = $1
`

func (q *Queries) GetFestivalByID(ctx context.Context, id pgtype.UUID) (Festival, error) {
	row := q.db.QueryRow(ctx, getFestivalByID, id)
	var i Festival
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.DateType,
		&i.Region,
		&i.HeritageType,
		&i.FestivalType,
		&i.Summary,
		&i.Story,
		&i.WhatToExpect,
		&i.HowToParticipate,
		&i.PracticalInfo,
		&i.CoverImageUrl,
		&i.GalleryImages,
		&i.VideoEmbeds,
		&i.IsPublished,
		&i.CreatedAt,
		&i.UsualMonth,
		&i.Date2026Start,
		&i.Date2026End,
	)
	return i, err
}

const getFestivalBySlug = `-- name: GetFestivalBySlug :one
SELECT id, slug, name, date_type, region, heritage_type, festival_type, summary, story, what_to_expect, how_to_participate, practical_info, cover_image_url, gallery_images, video_embeds, is_published, created_at, usual_month, date_2026_start, date_2026_end FROM festivals
WHERE slug = $1 AND is_published = true
`

func (q *Queries) GetFestivalBySlug(ctx context.Context, slug string) (Festival, error) {
	row := q.db.QueryRow(ctx, getFestivalBySlug, slug)
	var i Festival
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.DateType,
		&i.Region,
		&i.HeritageType,
		&i.FestivalType,
		&i.Summary,
		&i.Story,
		&i.WhatToExpect,
		&i.HowToParticipate,
		&i.PracticalInfo,
		&i.CoverImageUrl,
		&i.GalleryImages,
		&i.VideoEmbeds,
		&i.IsPublished,
		&i.CreatedAt,
		&i.UsualMonth,
		&i.Date2026Start,
		&i.Date2026End,
	)
	return i, err
}

const listFestivals = `-- name: ListFestivals :many
SELECT id, slug, name, date_type, region, heritage_type, festival_type, summary, story, what_to_expect, how_to_participate, practical_info, cover_image_url, gallery_images, video_embeds, is_published, created_at, usual_month, date_2026_start, date_2026_end FROM festivals
WHERE is_published = true
ORDER BY name ASC
`

func (q *Queries) ListFestivals(ctx context.Context) ([]Festival, error) {
	rows, err := q.db.Query(ctx, listFestivals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Festival{}
	for rows.Next() {
		var i Festival
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.DateType,
			&i.Region,
			&i.HeritageType,
			&i.FestivalType,
			&i.Summary,
			&i.Story,
			&i.WhatToExpect,
			&i.HowToParticipate,
			&i.PracticalInfo,
			&i.CoverImageUrl,
			&i.GalleryImages,
			&i.VideoEmbeds,
			&i.IsPublished,
			&i.CreatedAt,
			&i.UsualMonth,
			&i.Date2026Start,
			&i.Date2026End,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFestivalsByHeritage = `-- name: ListFestivalsByHeritage :many
SELECT id, slug, name, date_type, region, heritage_type, festival_type, summary, story, what_to_expect, how_to_participate, practical_info, cover_image_url, gallery_images, video_embeds, is_published, created_at, usual_month, date_2026_start, date_2026_end FROM festivals
WHERE is_published = true AND heritage_type = $1
ORDER BY name ASC
`

func (q *Queries) ListFestivalsByHeritage(ctx context.Context, heritageType string) ([]Festival, error) {
	rows, err := q.db.Query(ctx, listFestivalsByHeritage, heritageType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Festival{}
	for rows.Next() {
		var i Festival
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.DateType,
			&i.Region,
			&i.HeritageType,
			&i.FestivalType,
			&i.Summary,
			&i.Story,
			&i.WhatToExpect,
			&i.HowToParticipate,
			&i.PracticalInfo,
			&i.CoverImageUrl,
			&i.GalleryImages,
			&i.VideoEmbeds,
			&i.IsPublished,
			&i.CreatedAt,
			&i.UsualMonth,
			&i.Date2026Start,
			&i.Date2026End,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFestivalsByRegion = `-- name: ListFestivalsByRegion :many
SELECT id, slug, name, date_type, region, heritage_type, festival_type, summary, story, what_to_expect, how_to_participate, practical_info, cover_image_url, gallery_images, video_embeds, is_published, created_at, usual_month, date_2026_start, date_2026_end FROM festivals
WHERE is_published = true AND region = $1
ORDER BY name ASC
`

func (q *Queries) ListFestivalsByRegion(ctx context.Context, region string) ([]Festival, error) {
	rows, err := q.db.Query(ctx, listFestivalsByRegion, region)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Festival{}
	for rows.Next() {
		var i Festival
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.DateType,
			&i.Region,
			&i.HeritageType,
			&i.FestivalType,
			&i.Summary,
			&i.Story,
			&i.WhatToExpect,
			&i.HowToParticipate,
			&i.PracticalInfo,
			&i.CoverImageUrl,
			&i.GalleryImages,
			&i.VideoEmbeds,
			&i.IsPublished,
			&i.CreatedAt,
			&i.UsualMonth,
			&i.Date2026Start,
			&i.Date2026End,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFestival = `-- name: UpdateFestival :one
UPDATE festivals SET
    slug = $2,
    name = $3,
    date_type = $4,
    region = $5,
    heritage_type = $6,
    festival_type = $7,
    summary = $8,
    story = $9,
    what_to_expect = $10,
    how_to_participate = $11,
    practical_info = $12,
    cover_image_url = $13,
    gallery_images = $14,
    video_embeds = $15,
    is_published = $16
WHERE id = $1
RETURNING id, slug, name, date_type, region, heritage_type, festival_type, summary, story, what_to_expect, how_to_participate, practical_info, cover_image_url, gallery_images, video_embeds, is_published, created_at, usual_month, date_2026_start, date_2026_end
`

type UpdateFestivalParams struct {
	ID               pgtype.UUID `json:"id"`
	Slug             string      `json:"slug"`
	Name             string      `json:"name"`
	DateType         string      `json:"dateType"`
	Region           string      `json:"region"`
	HeritageType     string      `json:"heritageType"`
	FestivalType     string      `json:"festivalType"`
	Summary          string      `json:"summary"`
	Story            pgtype.Text `json:"story"`
	WhatToExpect     pgtype.Text `json:"whatToExpect"`
	HowToParticipate pgtype.Text `json:"howToParticipate"`
	PracticalInfo    pgtype.Text `json:"practicalInfo"`
	CoverImageUrl    pgtype.Text `json:"coverImageUrl"`
	GalleryImages    []byte      `json:"galleryImages"`
	VideoEmbeds      []byte      `json:"videoEmbeds"`
	IsPublished      pgtype.Bool `json:"isPublished"`
}

func (q *Queries) UpdateFestival(ctx context.Context, arg UpdateFestivalParams) (Festival, error) {
	row := q.db.QueryRow(ctx, updateFestival,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.DateType,
		arg.Region,
		arg.HeritageType,
		arg.FestivalType,
		arg.Summary,
		arg.Story,
		arg.WhatToExpect,
		arg.HowToParticipate,
		arg.PracticalInfo,
		arg.CoverImageUrl,
		arg.GalleryImages,
		arg.VideoEmbeds,
		arg.IsPublished,
	)
	var i Festival
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.DateType,
		&i.Region,
		&i.HeritageType,
		&i.FestivalType,
		&i.Summary,
		&i.Story,
		&i.WhatToExpect,
		&i.HowToParticipate,
		&i.PracticalInfo,
		&i.CoverImageUrl,
		&i.GalleryImages,
		&i.VideoEmbeds,
		&i.IsPublished,
		&i.CreatedAt,
		&i.UsualMonth,
		&i.Date2026Start,
		&i.Date2026End,
	)
	return i, err
}
